### ISSUE TITLE
Workflow - npm publish

### ISSUE THREAD

**Issue by cenobitedk** [kasperpihl/react-slice#4]
I'm planning to set up this action:
https://github.com/marketplace/actions/npm-publish

For this we need an NPM _TOKEN which I believe you need to add @kasperpihl.

**Comment by kasperpihl** [comment]
Sounds good, where should I add it?

**Comment by kasperpihl** [comment]
@cenobitedk just added it as a secret to this project

**Comment by cenobitedk** [comment]
@kasperpihl  Thanks!

**Comment by cenobitedk** [comment]
Fixed in #5
